version: '3'

services:
  db:
    image: postgres:13
    container_name: test_db
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    volumes:
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"