"""8th

Revision ID: 096831dfa390
Revises: 9e6740035cef
Create Date: 2022-01-22 01:04:36.730321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096831dfa390'
down_revision = '9e6740035cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
